[phases.setup]
nixPkgs = ["nodejs_22"]

[phases.install]
cmds = [
  "npm install -g pnpm@10.28.2 && ln -sf $(npm bin -g)/pnpm /usr/bin/pnpm",
  "pnpm install --frozen-lockfile"
]

[phases.build]
cmds = ["pnpm --filter api build"]

[start]
cmd = "pnpm --filter api start:prod"
