ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'PASSWORD_RESET_REQUESTED';

ALTER TABLE "PropertyHold"
ADD COLUMN IF NOT EXISTS "adults" INTEGER NOT NULL DEFAULT 1,
ADD COLUMN IF NOT EXISTS "children" INTEGER NOT NULL DEFAULT 0;