ALTER TABLE "Property"
  ADD COLUMN IF NOT EXISTS "reviewHistory" JSONB NOT NULL DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS "lastSubmittedAt" TIMESTAMP(3),
  ADD COLUMN IF NOT EXISTS "lastReviewedAt" TIMESTAMP(3),
  ADD COLUMN IF NOT EXISTS "lastEditedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;

UPDATE "Property"
SET "lastEditedAt" = COALESCE("lastEditedAt", "updatedAt", CURRENT_TIMESTAMP)
WHERE "lastEditedAt" IS NULL;
